training_method: "test_ranking"


batch_size: 1
num_dataloader_workers: 8

model:
  name: "PipelineDatasetSurrogateModel"
  model_parameters:
    pipe_encoder_type: "graph_transformer"
    dataset_encoder_type: "column"

dataset_params:
  root_path: "./data/pymfe_meta_features_and_fedot_pipelines/all"

model_data:
  save_dir: "./experiments/base/"
